name: Master Branch
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: Build and deploy to Ali OSS
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"

      - name: Build
        run: |
          npm install
          npm run build --prod

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint:  "oss-cn-hongkong.aliyuncs.com"
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      - name: Deploy To OSS
        run: ossutil cp dist oss://internal-fe/ -rf